name: techdocs

on:
  push:
    branches: [ $default-branch ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/techdocs.yaml'

permissions: write-all

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Build and publish techdocs
        uses: Updater/action-techdocs@main
        with:
          aws-role-arn: ${{ secrets.OIDC_ROLE_ARN_TECHDOCS_PUBLISH }}
