---
name: PR - Fossa

on:
  pull_request:
  workflow_dispatch:

env:
  FOSSA_TELEMETRY_SCOPE: off

jobs:
  fossa:
    uses: Updater/.github/.github/workflows/fossa.yaml@main
    secrets:
      fossa-api-key: ${{ secrets.FOSSA_API_KEY }}
      token: ${{ github.token }}
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.ref }}
