---
name: PR - Fossa

on:
  pull_request:
  workflow_dispatch:

env:
  FOSSA_TELEMETRY_SCOPE: off

jobs:
  fossa:
    continue-on-error: true
    uses: ./.github/workflows/fossa.yaml
    secrets:
      fossa-api-key: ${{ secrets.FOSSA_API_KEY }}
      token: ${{ github.token }}
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.ref }}
